// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using demoAPI.Models;

#nullable disable

namespace demoAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("demoAPI.Models.Entity.DistrictEntity", b =>
                {
                    b.Property<int>("districtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("districtid"));

                    b.Property<string>("districtname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("stateid")
                        .HasColumnType("integer");

                    b.HasKey("districtid");

                    b.ToTable("district");
                });

            modelBuilder.Entity("demoAPI.Models.Entity.StateEntity", b =>
                {
                    b.Property<int>("stateid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("stateid"));

                    b.Property<string>("statename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("stateid");

                    b.ToTable("state");
                });
#pragma warning restore 612, 618
        }
    }
}
